<?php

namespace App;

use App\Observers\SpacialCategoryObserver;
use Illuminate\Database\Eloquent\Model;

class SpacialCategory extends Model
{
    protected $fillable = array('name', 'store_id', 'status');

    protected $observables = [
        'statusUpdated',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        SpacialCategory::observe(SpacialCategoryObserver::class);
    }

    public function store()
    {
        return $this->belongsTo('App\Store');
    }

    public function products(){
        return $this->hasMany('App\Product', 'spacialCategory_id', 'id');
    }
}
